- name: Get server IP address
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: target_host
      prompt: Please enter target IP or hostname
      private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- name: Provision target
  hosts: dynamically_created_hosts
  become: yes
  remote_user: sysadmin
  vars:
    host_release_name: buster
  roles:
    - common
    - security
    - nginx
    - docker
    - certbot
